import os
from langchain_groq import ChatGroq
from state import State
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from typing import List
from langchain_community.tools import DuckDuckGoSearchRun

load_dotenv()

api_key = os.getenv("GROQ_API_KEY")

model = ChatGroq(
    api_key=api_key,
    model="llama-3.1-8b-instant",
    temperature=0.7,
)

search_tool = DuckDuckGoSearchRun()

class PlannerOutput(BaseModel):
    tasks: List[str] = Field(..., description="List of tasks generated by the planner")

structured_llm = model.with_structured_output(PlannerOutput)



def researcher(state: State) :
    tasks = state['tasks']
    search_query = ", ".join(tasks)
    search_result = search_tool.invoke(search_query)
    return {
        "research_data" : search_result
    }


def PlannerOutput(BaseModel):
    tasks: List[str] = Field(..., description="List of tasks generated by the planner")
    require_research: bool = Field(..., description="Whether research is required for these tasks")
    structured_llm = model.with_structured_output(PlannerOutput)


def planner(state: State) :
    user_message = state["user_message"]
    prompt = f"""  Break this user request into simple tasks.

    User Request:
    {user_message}

    Return tasks as bullet points.
    """
    response = structured_llm.invoke(prompt)
    tasks = response.tasks
    require_research = response.require_research
    return {
        "tasks": tasks,
        "require_research": require_research
    }




def chatbot(state: State)  :
    tasks = state["tasks"]
    research_data = state["research_data"]
    prompt = f"""
    Complete these tasks:

    {tasks}

    Using this research data:

    {research_data}

    Generate a final response.
    """


    response = model.invoke(prompt)
    return{
        "response" : response.content
    }